console.log(' [-] Trigger Thinky to setup database and tables')
require('./server/models/Game')
require('./server/models/Player')
require('./server/models/GameHistory')
console.log(' | Check the database and exit when everything is setup')
