// flow-typed signature: 99c8f6c05d9ae2de20752b1d3a9a75fe
// flow-typed version: <<STUB>>/audio-play_v^2.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'audio-play'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'audio-play' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'audio-play/browser' {
  declare module.exports: any;
}

declare module 'audio-play/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'audio-play/browser.js' {
  declare module.exports: $Exports<'audio-play/browser'>;
}
declare module 'audio-play/index' {
  declare module.exports: $Exports<'audio-play'>;
}
declare module 'audio-play/index.js' {
  declare module.exports: $Exports<'audio-play'>;
}
declare module 'audio-play/test.js' {
  declare module.exports: $Exports<'audio-play/test'>;
}
