// flow-typed signature: bb060bb210840954c83f7f7ad961664d
// flow-typed version: <<STUB>>/audio-loader_v^0.6.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'audio-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'audio-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'audio-loader/dist/audio-loader.min' {
  declare module.exports: any;
}

declare module 'audio-loader/lib/base64' {
  declare module.exports: any;
}

declare module 'audio-loader/lib/browser' {
  declare module.exports: any;
}

declare module 'audio-loader/lib/index' {
  declare module.exports: any;
}

declare module 'audio-loader/lib/load' {
  declare module.exports: any;
}

declare module 'audio-loader/test/browser-test' {
  declare module.exports: any;
}

declare module 'audio-loader/test/node-test' {
  declare module.exports: any;
}

declare module 'audio-loader/test/support/piano' {
  declare module.exports: any;
}

declare module 'audio-loader/test/support/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'audio-loader/dist/audio-loader.min.js' {
  declare module.exports: $Exports<'audio-loader/dist/audio-loader.min'>;
}
declare module 'audio-loader/lib/base64.js' {
  declare module.exports: $Exports<'audio-loader/lib/base64'>;
}
declare module 'audio-loader/lib/browser.js' {
  declare module.exports: $Exports<'audio-loader/lib/browser'>;
}
declare module 'audio-loader/lib/index.js' {
  declare module.exports: $Exports<'audio-loader/lib/index'>;
}
declare module 'audio-loader/lib/load.js' {
  declare module.exports: $Exports<'audio-loader/lib/load'>;
}
declare module 'audio-loader/test/browser-test.js' {
  declare module.exports: $Exports<'audio-loader/test/browser-test'>;
}
declare module 'audio-loader/test/node-test.js' {
  declare module.exports: $Exports<'audio-loader/test/node-test'>;
}
declare module 'audio-loader/test/support/piano.js' {
  declare module.exports: $Exports<'audio-loader/test/support/piano'>;
}
declare module 'audio-loader/test/support/utils.js' {
  declare module.exports: $Exports<'audio-loader/test/support/utils'>;
}
