// flow-typed signature: 12b0c48ad121555e0e9f8317775df0a4
// flow-typed version: <<STUB>>/babel-plugin-transform-flow-strip-types_v^6.18.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-flow-strip-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-flow-strip-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-flow-strip-types/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-flow-strip-types/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-flow-strip-types/lib/index'>;
}
