// flow-typed signature: a1d8b7ebbfee084b37b1f5187e4d5637
// flow-typed version: <<STUB>>/compression_v^1.6.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compression/index' {
  declare module.exports: $Exports<'compression'>;
}
declare module 'compression/index.js' {
  declare module.exports: $Exports<'compression'>;
}
