// flow-typed signature: 04f922518c49235a99d56acec41911fd
// flow-typed version: <<STUB>>/history_v1.13.x/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'history/lib/Actions' {
  declare module.exports: any;
}

declare module 'history/lib/AsyncUtils' {
  declare module.exports: any;
}

declare module 'history/lib/createBrowserHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createDOMHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createHashHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createHistory' {
  declare module.exports: any;
}

declare module 'history/lib/createLocation' {
  declare module.exports: any;
}

declare module 'history/lib/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'history/lib/deprecate' {
  declare module.exports: any;
}

declare module 'history/lib/DOMStateStorage' {
  declare module.exports: any;
}

declare module 'history/lib/DOMUtils' {
  declare module.exports: any;
}

declare module 'history/lib/enableBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/lib/enableQueries' {
  declare module.exports: any;
}

declare module 'history/lib/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'history/lib/extractPath' {
  declare module.exports: any;
}

declare module 'history/lib/index' {
  declare module.exports: any;
}

declare module 'history/lib/parsePath' {
  declare module.exports: any;
}

declare module 'history/lib/runTransitionHook' {
  declare module.exports: any;
}

declare module 'history/lib/useBasename' {
  declare module.exports: any;
}

declare module 'history/lib/useBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/lib/useQueries' {
  declare module.exports: any;
}

declare module 'history/modules/Actions' {
  declare module.exports: any;
}

declare module 'history/modules/AsyncUtils' {
  declare module.exports: any;
}

declare module 'history/modules/createBrowserHistory' {
  declare module.exports: any;
}

declare module 'history/modules/createDOMHistory' {
  declare module.exports: any;
}

declare module 'history/modules/createHashHistory' {
  declare module.exports: any;
}

declare module 'history/modules/createHistory' {
  declare module.exports: any;
}

declare module 'history/modules/createLocation' {
  declare module.exports: any;
}

declare module 'history/modules/createMemoryHistory' {
  declare module.exports: any;
}

declare module 'history/modules/deprecate' {
  declare module.exports: any;
}

declare module 'history/modules/DOMStateStorage' {
  declare module.exports: any;
}

declare module 'history/modules/DOMUtils' {
  declare module.exports: any;
}

declare module 'history/modules/enableBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/modules/enableQueries' {
  declare module.exports: any;
}

declare module 'history/modules/ExecutionEnvironment' {
  declare module.exports: any;
}

declare module 'history/modules/extractPath' {
  declare module.exports: any;
}

declare module 'history/modules/index' {
  declare module.exports: any;
}

declare module 'history/modules/parsePath' {
  declare module.exports: any;
}

declare module 'history/modules/runTransitionHook' {
  declare module.exports: any;
}

declare module 'history/modules/useBasename' {
  declare module.exports: any;
}

declare module 'history/modules/useBeforeUnload' {
  declare module.exports: any;
}

declare module 'history/modules/useQueries' {
  declare module.exports: any;
}

declare module 'history/npm-scripts/postinstall' {
  declare module.exports: any;
}

declare module 'history/umd/History' {
  declare module.exports: any;
}

declare module 'history/umd/History.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'history/lib/Actions.js' {
  declare module.exports: $Exports<'history/lib/Actions'>;
}
declare module 'history/lib/AsyncUtils.js' {
  declare module.exports: $Exports<'history/lib/AsyncUtils'>;
}
declare module 'history/lib/createBrowserHistory.js' {
  declare module.exports: $Exports<'history/lib/createBrowserHistory'>;
}
declare module 'history/lib/createDOMHistory.js' {
  declare module.exports: $Exports<'history/lib/createDOMHistory'>;
}
declare module 'history/lib/createHashHistory.js' {
  declare module.exports: $Exports<'history/lib/createHashHistory'>;
}
declare module 'history/lib/createHistory.js' {
  declare module.exports: $Exports<'history/lib/createHistory'>;
}
declare module 'history/lib/createLocation.js' {
  declare module.exports: $Exports<'history/lib/createLocation'>;
}
declare module 'history/lib/createMemoryHistory.js' {
  declare module.exports: $Exports<'history/lib/createMemoryHistory'>;
}
declare module 'history/lib/deprecate.js' {
  declare module.exports: $Exports<'history/lib/deprecate'>;
}
declare module 'history/lib/DOMStateStorage.js' {
  declare module.exports: $Exports<'history/lib/DOMStateStorage'>;
}
declare module 'history/lib/DOMUtils.js' {
  declare module.exports: $Exports<'history/lib/DOMUtils'>;
}
declare module 'history/lib/enableBeforeUnload.js' {
  declare module.exports: $Exports<'history/lib/enableBeforeUnload'>;
}
declare module 'history/lib/enableQueries.js' {
  declare module.exports: $Exports<'history/lib/enableQueries'>;
}
declare module 'history/lib/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'history/lib/ExecutionEnvironment'>;
}
declare module 'history/lib/extractPath.js' {
  declare module.exports: $Exports<'history/lib/extractPath'>;
}
declare module 'history/lib/index.js' {
  declare module.exports: $Exports<'history/lib/index'>;
}
declare module 'history/lib/parsePath.js' {
  declare module.exports: $Exports<'history/lib/parsePath'>;
}
declare module 'history/lib/runTransitionHook.js' {
  declare module.exports: $Exports<'history/lib/runTransitionHook'>;
}
declare module 'history/lib/useBasename.js' {
  declare module.exports: $Exports<'history/lib/useBasename'>;
}
declare module 'history/lib/useBeforeUnload.js' {
  declare module.exports: $Exports<'history/lib/useBeforeUnload'>;
}
declare module 'history/lib/useQueries.js' {
  declare module.exports: $Exports<'history/lib/useQueries'>;
}
declare module 'history/modules/Actions.js' {
  declare module.exports: $Exports<'history/modules/Actions'>;
}
declare module 'history/modules/AsyncUtils.js' {
  declare module.exports: $Exports<'history/modules/AsyncUtils'>;
}
declare module 'history/modules/createBrowserHistory.js' {
  declare module.exports: $Exports<'history/modules/createBrowserHistory'>;
}
declare module 'history/modules/createDOMHistory.js' {
  declare module.exports: $Exports<'history/modules/createDOMHistory'>;
}
declare module 'history/modules/createHashHistory.js' {
  declare module.exports: $Exports<'history/modules/createHashHistory'>;
}
declare module 'history/modules/createHistory.js' {
  declare module.exports: $Exports<'history/modules/createHistory'>;
}
declare module 'history/modules/createLocation.js' {
  declare module.exports: $Exports<'history/modules/createLocation'>;
}
declare module 'history/modules/createMemoryHistory.js' {
  declare module.exports: $Exports<'history/modules/createMemoryHistory'>;
}
declare module 'history/modules/deprecate.js' {
  declare module.exports: $Exports<'history/modules/deprecate'>;
}
declare module 'history/modules/DOMStateStorage.js' {
  declare module.exports: $Exports<'history/modules/DOMStateStorage'>;
}
declare module 'history/modules/DOMUtils.js' {
  declare module.exports: $Exports<'history/modules/DOMUtils'>;
}
declare module 'history/modules/enableBeforeUnload.js' {
  declare module.exports: $Exports<'history/modules/enableBeforeUnload'>;
}
declare module 'history/modules/enableQueries.js' {
  declare module.exports: $Exports<'history/modules/enableQueries'>;
}
declare module 'history/modules/ExecutionEnvironment.js' {
  declare module.exports: $Exports<'history/modules/ExecutionEnvironment'>;
}
declare module 'history/modules/extractPath.js' {
  declare module.exports: $Exports<'history/modules/extractPath'>;
}
declare module 'history/modules/index.js' {
  declare module.exports: $Exports<'history/modules/index'>;
}
declare module 'history/modules/parsePath.js' {
  declare module.exports: $Exports<'history/modules/parsePath'>;
}
declare module 'history/modules/runTransitionHook.js' {
  declare module.exports: $Exports<'history/modules/runTransitionHook'>;
}
declare module 'history/modules/useBasename.js' {
  declare module.exports: $Exports<'history/modules/useBasename'>;
}
declare module 'history/modules/useBeforeUnload.js' {
  declare module.exports: $Exports<'history/modules/useBeforeUnload'>;
}
declare module 'history/modules/useQueries.js' {
  declare module.exports: $Exports<'history/modules/useQueries'>;
}
declare module 'history/npm-scripts/postinstall.js' {
  declare module.exports: $Exports<'history/npm-scripts/postinstall'>;
}
declare module 'history/umd/History.js' {
  declare module.exports: $Exports<'history/umd/History'>;
}
declare module 'history/umd/History.min.js' {
  declare module.exports: $Exports<'history/umd/History.min'>;
}
