// flow-typed signature: 518180af917dbd1f07c1f90b2cefdbdf
// flow-typed version: <<STUB>>/karma-webpack_v1.7.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-webpack/mocha-env-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-webpack/index' {
  declare module.exports: $Exports<'karma-webpack'>;
}
declare module 'karma-webpack/index.js' {
  declare module.exports: $Exports<'karma-webpack'>;
}
declare module 'karma-webpack/mocha-env-loader.js' {
  declare module.exports: $Exports<'karma-webpack/mocha-env-loader'>;
}
