// flow-typed signature: b3027404a991748a0c18f4421e6c3a23
// flow-typed version: <<STUB>>/karma-testdouble_v^1.0.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-testdouble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-testdouble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-testdouble/index' {
  declare module.exports: $Exports<'karma-testdouble'>;
}
declare module 'karma-testdouble/index.js' {
  declare module.exports: $Exports<'karma-testdouble'>;
}
