// flow-typed signature: 49f3c4d3e48fb10a6220c1ed9f379e9f
// flow-typed version: <<STUB>>/nib_v^1.1.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nib/lib/nib' {
  declare module.exports: any;
}

declare module 'nib/lib/nodes/color-image' {
  declare module.exports: any;
}

declare module 'nib/lib/nodes/gradient' {
  declare module.exports: any;
}

declare module 'nib/lib/nodes/vendor-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nib/lib/nib.js' {
  declare module.exports: $Exports<'nib/lib/nib'>;
}
declare module 'nib/lib/nodes/color-image.js' {
  declare module.exports: $Exports<'nib/lib/nodes/color-image'>;
}
declare module 'nib/lib/nodes/gradient.js' {
  declare module.exports: $Exports<'nib/lib/nodes/gradient'>;
}
declare module 'nib/lib/nodes/vendor-helpers.js' {
  declare module.exports: $Exports<'nib/lib/nodes/vendor-helpers'>;
}
