// flow-typed signature: 97597293ecb6c3ce5aa3be8cd4867c87
// flow-typed version: <<STUB>>/raw-loader_v0.5.x/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raw-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'raw-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'raw-loader/index' {
  declare module.exports: $Exports<'raw-loader'>;
}
declare module 'raw-loader/index.js' {
  declare module.exports: $Exports<'raw-loader'>;
}
