// flow-typed signature: 3e5213688df64edce76d18d5fdfe10d5
// flow-typed version: <<STUB>>/testdouble_v^1.10.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testdouble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'testdouble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testdouble/dist/testdouble' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/adder' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/calculator' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/car' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/multiplier' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/subtractor' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/lib/vehicle' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/test/helper' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/test/lib/calculator-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/babel/test/lib/car-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/application' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/files' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/lineman' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/config/server' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/Gruntfile' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/spec/helpers/helper' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/spec/math-problem-spec' {
  declare module.exports: any;
}

declare module 'testdouble/examples/lineman/vendor/js/underscore' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/accelerometer' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/brake' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/car' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/lib/gas-pedal' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/test/helper' {
  declare module.exports: any;
}

declare module 'testdouble/examples/node/test/lib/car-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/webpack/test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/webpack/test/math-problem-test' {
  declare module.exports: any;
}

declare module 'testdouble/examples/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/browser-helper' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/fixtures/car' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/fixtures/honk' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/fixtures/lights' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/fixtures/passenger' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/general-helper' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/node-helper' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/args-match-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/callback-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/captor-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/config-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/explain-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/log-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/matchers-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/object-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/replace/index-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/store/index-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/stringify/anything-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/testdouble-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/verify-test' {
  declare module.exports: any;
}

declare module 'testdouble/generated/test/src/when-test' {
  declare module.exports: any;
}

declare module 'testdouble/lib/args-match' {
  declare module.exports: any;
}

declare module 'testdouble/lib/config' {
  declare module.exports: any;
}

declare module 'testdouble/lib/explain' {
  declare module.exports: any;
}

declare module 'testdouble/lib/function' {
  declare module.exports: any;
}

declare module 'testdouble/lib/log' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/callback' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/captor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/create' {
  declare module.exports: any;
}

declare module 'testdouble/lib/matchers/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/object' {
  declare module.exports: any;
}

declare module 'testdouble/lib/quibble.browser' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/imitate' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/is-constructor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/module.browser' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/module' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/property' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/wrap-if-needed' {
  declare module.exports: any;
}

declare module 'testdouble/lib/replace/wrap-with-constructor' {
  declare module.exports: any;
}

declare module 'testdouble/lib/reset' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/calls' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/index' {
  declare module.exports: any;
}

declare module 'testdouble/lib/store/stubbings' {
  declare module.exports: any;
}

declare module 'testdouble/lib/stringify/anything' {
  declare module.exports: any;
}

declare module 'testdouble/lib/stringify/arguments' {
  declare module.exports: any;
}

declare module 'testdouble/lib/testdouble' {
  declare module.exports: any;
}

declare module 'testdouble/lib/util/clone-with-non-enumerable-properties' {
  declare module.exports: any;
}

declare module 'testdouble/lib/util/lodash-wrap' {
  declare module.exports: any;
}

declare module 'testdouble/lib/verify' {
  declare module.exports: any;
}

declare module 'testdouble/lib/version' {
  declare module.exports: any;
}

declare module 'testdouble/lib/when' {
  declare module.exports: any;
}

declare module 'testdouble/test/fixtures/es6class' {
  declare module.exports: any;
}

declare module 'testdouble/test/fixtures/turn' {
  declare module.exports: any;
}

declare module 'testdouble/testem' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testdouble/dist/testdouble.js' {
  declare module.exports: $Exports<'testdouble/dist/testdouble'>;
}
declare module 'testdouble/examples/babel/lib/adder.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/adder'>;
}
declare module 'testdouble/examples/babel/lib/calculator.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/calculator'>;
}
declare module 'testdouble/examples/babel/lib/car.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/car'>;
}
declare module 'testdouble/examples/babel/lib/multiplier.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/multiplier'>;
}
declare module 'testdouble/examples/babel/lib/subtractor.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/subtractor'>;
}
declare module 'testdouble/examples/babel/lib/vehicle.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/lib/vehicle'>;
}
declare module 'testdouble/examples/babel/test/helper.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/test/helper'>;
}
declare module 'testdouble/examples/babel/test/lib/calculator-test.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/test/lib/calculator-test'>;
}
declare module 'testdouble/examples/babel/test/lib/car-test.js' {
  declare module.exports: $Exports<'testdouble/examples/babel/test/lib/car-test'>;
}
declare module 'testdouble/examples/lineman/config/application.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/application'>;
}
declare module 'testdouble/examples/lineman/config/files.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/files'>;
}
declare module 'testdouble/examples/lineman/config/lineman.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/lineman'>;
}
declare module 'testdouble/examples/lineman/config/server.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/config/server'>;
}
declare module 'testdouble/examples/lineman/Gruntfile.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/Gruntfile'>;
}
declare module 'testdouble/examples/lineman/spec/helpers/helper.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/spec/helpers/helper'>;
}
declare module 'testdouble/examples/lineman/spec/math-problem-spec.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/spec/math-problem-spec'>;
}
declare module 'testdouble/examples/lineman/vendor/js/underscore.js' {
  declare module.exports: $Exports<'testdouble/examples/lineman/vendor/js/underscore'>;
}
declare module 'testdouble/examples/node/lib/accelerometer.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/accelerometer'>;
}
declare module 'testdouble/examples/node/lib/brake.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/brake'>;
}
declare module 'testdouble/examples/node/lib/car.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/car'>;
}
declare module 'testdouble/examples/node/lib/gas-pedal.js' {
  declare module.exports: $Exports<'testdouble/examples/node/lib/gas-pedal'>;
}
declare module 'testdouble/examples/node/test/helper.js' {
  declare module.exports: $Exports<'testdouble/examples/node/test/helper'>;
}
declare module 'testdouble/examples/node/test/lib/car-test.js' {
  declare module.exports: $Exports<'testdouble/examples/node/test/lib/car-test'>;
}
declare module 'testdouble/examples/webpack/test.js' {
  declare module.exports: $Exports<'testdouble/examples/webpack/test'>;
}
declare module 'testdouble/examples/webpack/test/math-problem-test.js' {
  declare module.exports: $Exports<'testdouble/examples/webpack/test/math-problem-test'>;
}
declare module 'testdouble/examples/webpack/webpack.config.js' {
  declare module.exports: $Exports<'testdouble/examples/webpack/webpack.config'>;
}
declare module 'testdouble/generated/test/browser-helper.js' {
  declare module.exports: $Exports<'testdouble/generated/test/browser-helper'>;
}
declare module 'testdouble/generated/test/fixtures/car.js' {
  declare module.exports: $Exports<'testdouble/generated/test/fixtures/car'>;
}
declare module 'testdouble/generated/test/fixtures/honk.js' {
  declare module.exports: $Exports<'testdouble/generated/test/fixtures/honk'>;
}
declare module 'testdouble/generated/test/fixtures/lights.js' {
  declare module.exports: $Exports<'testdouble/generated/test/fixtures/lights'>;
}
declare module 'testdouble/generated/test/fixtures/passenger.js' {
  declare module.exports: $Exports<'testdouble/generated/test/fixtures/passenger'>;
}
declare module 'testdouble/generated/test/general-helper.js' {
  declare module.exports: $Exports<'testdouble/generated/test/general-helper'>;
}
declare module 'testdouble/generated/test/node-helper.js' {
  declare module.exports: $Exports<'testdouble/generated/test/node-helper'>;
}
declare module 'testdouble/generated/test/src/args-match-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/args-match-test'>;
}
declare module 'testdouble/generated/test/src/callback-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/callback-test'>;
}
declare module 'testdouble/generated/test/src/captor-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/captor-test'>;
}
declare module 'testdouble/generated/test/src/config-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/config-test'>;
}
declare module 'testdouble/generated/test/src/explain-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/explain-test'>;
}
declare module 'testdouble/generated/test/src/log-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/log-test'>;
}
declare module 'testdouble/generated/test/src/matchers-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/matchers-test'>;
}
declare module 'testdouble/generated/test/src/object-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/object-test'>;
}
declare module 'testdouble/generated/test/src/replace/index-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/replace/index-test'>;
}
declare module 'testdouble/generated/test/src/store/index-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/store/index-test'>;
}
declare module 'testdouble/generated/test/src/stringify/anything-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/stringify/anything-test'>;
}
declare module 'testdouble/generated/test/src/testdouble-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/testdouble-test'>;
}
declare module 'testdouble/generated/test/src/verify-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/verify-test'>;
}
declare module 'testdouble/generated/test/src/when-test.js' {
  declare module.exports: $Exports<'testdouble/generated/test/src/when-test'>;
}
declare module 'testdouble/lib/args-match.js' {
  declare module.exports: $Exports<'testdouble/lib/args-match'>;
}
declare module 'testdouble/lib/config.js' {
  declare module.exports: $Exports<'testdouble/lib/config'>;
}
declare module 'testdouble/lib/explain.js' {
  declare module.exports: $Exports<'testdouble/lib/explain'>;
}
declare module 'testdouble/lib/function.js' {
  declare module.exports: $Exports<'testdouble/lib/function'>;
}
declare module 'testdouble/lib/log.js' {
  declare module.exports: $Exports<'testdouble/lib/log'>;
}
declare module 'testdouble/lib/matchers/callback.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/callback'>;
}
declare module 'testdouble/lib/matchers/captor.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/captor'>;
}
declare module 'testdouble/lib/matchers/create.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/create'>;
}
declare module 'testdouble/lib/matchers/index.js' {
  declare module.exports: $Exports<'testdouble/lib/matchers/index'>;
}
declare module 'testdouble/lib/object.js' {
  declare module.exports: $Exports<'testdouble/lib/object'>;
}
declare module 'testdouble/lib/quibble.browser.js' {
  declare module.exports: $Exports<'testdouble/lib/quibble.browser'>;
}
declare module 'testdouble/lib/replace/imitate.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/imitate'>;
}
declare module 'testdouble/lib/replace/index.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/index'>;
}
declare module 'testdouble/lib/replace/is-constructor.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/is-constructor'>;
}
declare module 'testdouble/lib/replace/module.browser.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/module.browser'>;
}
declare module 'testdouble/lib/replace/module.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/module'>;
}
declare module 'testdouble/lib/replace/property.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/property'>;
}
declare module 'testdouble/lib/replace/wrap-if-needed.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/wrap-if-needed'>;
}
declare module 'testdouble/lib/replace/wrap-with-constructor.js' {
  declare module.exports: $Exports<'testdouble/lib/replace/wrap-with-constructor'>;
}
declare module 'testdouble/lib/reset.js' {
  declare module.exports: $Exports<'testdouble/lib/reset'>;
}
declare module 'testdouble/lib/store/calls.js' {
  declare module.exports: $Exports<'testdouble/lib/store/calls'>;
}
declare module 'testdouble/lib/store/index.js' {
  declare module.exports: $Exports<'testdouble/lib/store/index'>;
}
declare module 'testdouble/lib/store/stubbings.js' {
  declare module.exports: $Exports<'testdouble/lib/store/stubbings'>;
}
declare module 'testdouble/lib/stringify/anything.js' {
  declare module.exports: $Exports<'testdouble/lib/stringify/anything'>;
}
declare module 'testdouble/lib/stringify/arguments.js' {
  declare module.exports: $Exports<'testdouble/lib/stringify/arguments'>;
}
declare module 'testdouble/lib/testdouble.js' {
  declare module.exports: $Exports<'testdouble/lib/testdouble'>;
}
declare module 'testdouble/lib/util/clone-with-non-enumerable-properties.js' {
  declare module.exports: $Exports<'testdouble/lib/util/clone-with-non-enumerable-properties'>;
}
declare module 'testdouble/lib/util/lodash-wrap.js' {
  declare module.exports: $Exports<'testdouble/lib/util/lodash-wrap'>;
}
declare module 'testdouble/lib/verify.js' {
  declare module.exports: $Exports<'testdouble/lib/verify'>;
}
declare module 'testdouble/lib/version.js' {
  declare module.exports: $Exports<'testdouble/lib/version'>;
}
declare module 'testdouble/lib/when.js' {
  declare module.exports: $Exports<'testdouble/lib/when'>;
}
declare module 'testdouble/test/fixtures/es6class.js' {
  declare module.exports: $Exports<'testdouble/test/fixtures/es6class'>;
}
declare module 'testdouble/test/fixtures/turn.js' {
  declare module.exports: $Exports<'testdouble/test/fixtures/turn'>;
}
declare module 'testdouble/testem.js' {
  declare module.exports: $Exports<'testdouble/testem'>;
}
