// flow-typed signature: 495be9441107673e9dcd1603da5d4b6c
// flow-typed version: <<STUB>>/thinky_v^2.3.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thinky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'thinky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'thinky/config' {
  declare module.exports: any;
}

declare module 'thinky/lib/document' {
  declare module.exports: any;
}

declare module 'thinky/lib/errors' {
  declare module.exports: any;
}

declare module 'thinky/lib/feed' {
  declare module.exports: any;
}

declare module 'thinky/lib/model' {
  declare module.exports: any;
}

declare module 'thinky/lib/query' {
  declare module.exports: any;
}

declare module 'thinky/lib/schema' {
  declare module.exports: any;
}

declare module 'thinky/lib/thinky' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/any' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/array' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/boolean' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/buffer' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/date' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/index' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/number' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/object' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/point' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/string' {
  declare module.exports: any;
}

declare module 'thinky/lib/type/virtual' {
  declare module.exports: any;
}

declare module 'thinky/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'thinky/config.js' {
  declare module.exports: $Exports<'thinky/config'>;
}
declare module 'thinky/lib/document.js' {
  declare module.exports: $Exports<'thinky/lib/document'>;
}
declare module 'thinky/lib/errors.js' {
  declare module.exports: $Exports<'thinky/lib/errors'>;
}
declare module 'thinky/lib/feed.js' {
  declare module.exports: $Exports<'thinky/lib/feed'>;
}
declare module 'thinky/lib/model.js' {
  declare module.exports: $Exports<'thinky/lib/model'>;
}
declare module 'thinky/lib/query.js' {
  declare module.exports: $Exports<'thinky/lib/query'>;
}
declare module 'thinky/lib/schema.js' {
  declare module.exports: $Exports<'thinky/lib/schema'>;
}
declare module 'thinky/lib/thinky.js' {
  declare module.exports: $Exports<'thinky/lib/thinky'>;
}
declare module 'thinky/lib/type/any.js' {
  declare module.exports: $Exports<'thinky/lib/type/any'>;
}
declare module 'thinky/lib/type/array.js' {
  declare module.exports: $Exports<'thinky/lib/type/array'>;
}
declare module 'thinky/lib/type/boolean.js' {
  declare module.exports: $Exports<'thinky/lib/type/boolean'>;
}
declare module 'thinky/lib/type/buffer.js' {
  declare module.exports: $Exports<'thinky/lib/type/buffer'>;
}
declare module 'thinky/lib/type/date.js' {
  declare module.exports: $Exports<'thinky/lib/type/date'>;
}
declare module 'thinky/lib/type/index.js' {
  declare module.exports: $Exports<'thinky/lib/type/index'>;
}
declare module 'thinky/lib/type/number.js' {
  declare module.exports: $Exports<'thinky/lib/type/number'>;
}
declare module 'thinky/lib/type/object.js' {
  declare module.exports: $Exports<'thinky/lib/type/object'>;
}
declare module 'thinky/lib/type/point.js' {
  declare module.exports: $Exports<'thinky/lib/type/point'>;
}
declare module 'thinky/lib/type/string.js' {
  declare module.exports: $Exports<'thinky/lib/type/string'>;
}
declare module 'thinky/lib/type/virtual.js' {
  declare module.exports: $Exports<'thinky/lib/type/virtual'>;
}
declare module 'thinky/lib/util.js' {
  declare module.exports: $Exports<'thinky/lib/util'>;
}
