// flow-typed signature: 95c2e1036e38906649113a96376bbc1c
// flow-typed version: <<STUB>>/@kadira/storybook-deployer_v^1.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook-deployer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook-deployer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook-deployer/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/storybook-deployer/src/utils.js' {
  declare module.exports: $Exports<'@kadira/storybook-deployer/src/utils'>;
}
